wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[   0.     -272.4622 -211.4385    0.       10.        0.     -188.7648\n\
    \  -127.6041    0.       10.        0.     -229.5817 -291.6857    0.\n    10.\
    \        0.       58.6624 -434.2028    0.       10.        0.\n   410.6424 -201.1071\
    \    0.        0.     -465.885   294.8054    0.\n     0.      144.2778 -219.968\
    \     0.        0.        0.        0.\n     0.        0.     -109.6908   66.3913\
    \    0.        0.      294.7074\n  -207.9226    0.        0.      451.3539 -246.5904\
    \    0.        0.\n     0.        0.        0.        0.      198.5888  428.4196\
    \    0.\n     0.      -79.489  -229.6501    0.        0.     -226.5645 -224.5941\n\
    \     0.        0.        0.        0.        0.        0.     -156.2665\n   \
    \ -5.2369    0.        0.      495.6193  -52.4622    0.        0.\n     0.   \
    \     0.        0.        0.        0.        0.        0.\n    90.      -80.9864\
    \ -466.1461    0.      100.       20.    ]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7febfc0cdd90>
_n_updates:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 2000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1633570910
    t:
      1:
      - 1
      4: 3.7.11
      5: 0.12.4
      8:
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(8)
algo:
  desc: null
  value: A2C
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fec0420de10>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0007
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fec04207b90>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2000
normalize_advantage:
  desc: null
  value: 'False'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-512. -512. -512. -512. -512. -512. -512. -512. -512. -512. -512. -512.\n\
    \ -512. -512. -512. -512. -512. -512. -512. -512. -512. -512. -512. -512.\n -512.\
    \ -512. -512. -512. -512. -512. -512. -512. -512. -512. -512. -512.\n -512. -512.\
    \ -512. -512. -512. -512. -512. -512. -512. -512. -512. -512.\n -512. -512. -512.\
    \ -512. -512. -512. -512. -512. -512. -512. -512. -512.\n -512. -512. -512. -512.\
    \ -512. -512. -512. -512. -512. -512. -512. -512.\n -512. -512. -512. -512. -512.\
    \ -512. -512. -512. -512. -512. -512. -512.\n -512. -512. -512. -512. -512. -512.],\
    \ [512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512.\
    \ 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512. 512.\
    \ 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512. 512. 512.\
    \ 512. 512. 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512. 512. 512. 512.\
    \ 512. 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512. 512. 512. 512. 512.\
    \ 512. 512. 512. 512. 512. 512. 512. 512. 512.\n 512. 512. 512. 512. 512. 512.],\
    \ (90,), float32)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=90,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=90, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''optimizer_class'': <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'':
    {''alpha'': 0.99, ''eps'': 1e-05, ''weight_decay'': 0}}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fec0420de50>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1633570911.7310336
tensorboard_log:
  desc: null
  value: None
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 0
vf_coef:
  desc: null
  value: 0.5
